//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApp.SearchTrophy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Trophy", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Trophy : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeagueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string League {
            get {
                return this.LeagueField;
            }
            set {
                if ((object.ReferenceEquals(this.LeagueField, value) != true)) {
                    this.LeagueField = value;
                    this.RaisePropertyChanged("League");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Season {
            get {
                return this.SeasonField;
            }
            set {
                if ((object.ReferenceEquals(this.SeasonField, value) != true)) {
                    this.SeasonField = value;
                    this.RaisePropertyChanged("Season");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Place {
            get {
                return this.PlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceField, value) != true)) {
                    this.PlaceField = value;
                    this.RaisePropertyChanged("Place");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SearchTrophy.TrophySearchServiceSoap")]
    public interface TrophySearchServiceSoap {
        
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchTrophies", ReplyAction="*")]
        ClientApp.SearchTrophy.SearchTrophiesResponse SearchTrophies(ClientApp.SearchTrophy.SearchTrophiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchTrophies", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientApp.SearchTrophy.SearchTrophiesResponse> SearchTrophiesAsync(ClientApp.SearchTrophy.SearchTrophiesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchTrophiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchTrophies", Namespace="http://tempuri.org/", Order=0)]
        public ClientApp.SearchTrophy.SearchTrophiesRequestBody Body;
        
        public SearchTrophiesRequest() {
        }
        
        public SearchTrophiesRequest(ClientApp.SearchTrophy.SearchTrophiesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchTrophiesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string value;
        
        public SearchTrophiesRequestBody() {
        }
        
        public SearchTrophiesRequestBody(string key, string value) {
            this.key = key;
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchTrophiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchTrophiesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientApp.SearchTrophy.SearchTrophiesResponseBody Body;
        
        public SearchTrophiesResponse() {
        }
        
        public SearchTrophiesResponse(ClientApp.SearchTrophy.SearchTrophiesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchTrophiesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientApp.SearchTrophy.Trophy[] SearchTrophiesResult;
        
        public SearchTrophiesResponseBody() {
        }
        
        public SearchTrophiesResponseBody(ClientApp.SearchTrophy.Trophy[] SearchTrophiesResult) {
            this.SearchTrophiesResult = SearchTrophiesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TrophySearchServiceSoapChannel : ClientApp.SearchTrophy.TrophySearchServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrophySearchServiceSoapClient : System.ServiceModel.ClientBase<ClientApp.SearchTrophy.TrophySearchServiceSoap>, ClientApp.SearchTrophy.TrophySearchServiceSoap {
        
        public TrophySearchServiceSoapClient() {
        }
        
        public TrophySearchServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrophySearchServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrophySearchServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrophySearchServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApp.SearchTrophy.SearchTrophiesResponse ClientApp.SearchTrophy.TrophySearchServiceSoap.SearchTrophies(ClientApp.SearchTrophy.SearchTrophiesRequest request) {
            return base.Channel.SearchTrophies(request);
        }
        
        public ClientApp.SearchTrophy.Trophy[] SearchTrophies(string key, string value) {
            ClientApp.SearchTrophy.SearchTrophiesRequest inValue = new ClientApp.SearchTrophy.SearchTrophiesRequest();
            inValue.Body = new ClientApp.SearchTrophy.SearchTrophiesRequestBody();
            inValue.Body.key = key;
            inValue.Body.value = value;
            ClientApp.SearchTrophy.SearchTrophiesResponse retVal = ((ClientApp.SearchTrophy.TrophySearchServiceSoap)(this)).SearchTrophies(inValue);
            return retVal.Body.SearchTrophiesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientApp.SearchTrophy.SearchTrophiesResponse> ClientApp.SearchTrophy.TrophySearchServiceSoap.SearchTrophiesAsync(ClientApp.SearchTrophy.SearchTrophiesRequest request) {
            return base.Channel.SearchTrophiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientApp.SearchTrophy.SearchTrophiesResponse> SearchTrophiesAsync(string key, string value) {
            ClientApp.SearchTrophy.SearchTrophiesRequest inValue = new ClientApp.SearchTrophy.SearchTrophiesRequest();
            inValue.Body = new ClientApp.SearchTrophy.SearchTrophiesRequestBody();
            inValue.Body.key = key;
            inValue.Body.value = value;
            return ((ClientApp.SearchTrophy.TrophySearchServiceSoap)(this)).SearchTrophiesAsync(inValue);
        }
    }
}
